from PIL import Image
im= Image.open("test.jpg")
r,g,b = im.split()
om = Image.merge("RGB",(b,g,r))
om.save('new1.jpg')
om = Image.merge("RGB",(b,r,g))
om.save('new2.jpg')
om = Image.merge("RGB",(g,b,r))
om.save('new3.jpg')
om = Image.merge("RGB",(g,r,b))
om.save('new4.jpg')
om = Image.merge("RGB",(r,b,g))
om.save('new5.jpg')
print("颜色交换成功")
print("处理完成")